Algoritmo "CalculadoraBasica"

// Fazer um programa para apresentar a soma,
// subtração e multiplicação de dois números inteiros

Var

n1,n2,soma,subtracao,divisao,multiplicacao:inteiro

Inicio

Escreval("Digite 2 números inteiros: ")
leia(n1)
leia(n2)

soma <- n1 + n2
multiplicacao <- n1 * n2
subtracao <- n1 - n2
divisao <- n1 div n2

Escreval("SOMA: ",soma)
Escreval("MULTIPLICACAO: ",multiplicacao)
Escreval("DIVISAO: ",divisao)
Escreval("SUBTRACAO: ",subtracao)


Fimalgoritmo