Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/07/2022
Var
// Seção de Declarações das variáveis 

ESTADO:caractere

Inicio

leia(ESTADO)

ESCOLHA ESTADO
       CASO ("RECIFE")
            ESCREVAL("Estado Nordestino")
FIMESCOLHA

Fimalgoritmo